postgresql_settings: &postgresql_settings
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: [YOUR_POSTGRES_USER]
  password: [YOUR_POSTGRES_PASSWORD]
  host: [YOUR_POSTGRES_IPV4_ADDRESS]
  database: [YOUR_POSTGRES_DATABASE]

development:
  <<: *postgresql_settings

production:
  <<: *postgresql_settings

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
